version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - '1435:1435'    
    expose:
      - 1435
    depends_on:
      - sqlserver
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: 'sqlserver'
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: "Numsey#2021"
    volumes:
      - c:\dados\volumes\mssql:/var/opt/mssql3
    ports:
      - '1433:1433'    
    expose:
      - 1433
